### ISSUE TITLE
So no one in the west has more that two given names?

### ISSUE THREAD

**Issue by kwhitefoot** [datamade/probablepeople#16] opened 2015-04-16 13:03 UTC
Frederick James Jonathan Bull-White

Is three given names followed by a hyphenated family name.  

I just made it up, but it is representative of a substantial subset of the English speaking population of the world.

Have looked at Spanish naming conventions?

Without a substantial amount of context I think that such parser cannot be made to be useful.

**Comment by fgregg** [comment] 2015-04-16 13:08
duplicate of #8 If you can point us to a list of names that have this pattern, please let us know in that issue.

**Closed by fgregg** 2015-04-16 13:08 UTC
